language: cpp
cache: apt

before_install:
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots

install:
  - sudo apt-get -y -qq update
  - sudo apt-get install -y curl make libgc-dev
  - sudo apt-get install --force-yes libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2
  - sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
  - sudo apt-get install -y caca-utils
  - pkg-config --exists libsdl2 && pkg-config --libs --cflags libsdl2

script:
  - make buildcpp
  - ./build/rays.out
  - img2txt screenshot.png



