language: cpp
sudo: false

addons:
  apt:
    sources:
      - ppa:kalakris/cmake
      - ppa:team-xbmc/ppa
   packages:
     - cmake
     - libXxf86vm-dev
     - libsdl2-dev

script:
  - make build
  - ./build/rays.out
