language: cpp
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq

install:
 - sudo apt-get install -y libXxf86vm-dev cmake libsdl2-dev

script:
  - make build
  - ./build/rays.out
